# application-prod.yml

server:
  port: 8080

spring:
  profiles:
    include: secret

  datasource:
    url: jdbc:mysql://localhost:3306/coursecatch_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
          google:
            redirect-uri: https://localhost:8080/login/oauth2/code/google

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.hibernate.SQL: INFO
    com.Catch_Course: INFO