# application.yml
server:
  port: 8080

spring:
  profiles:
    include: secret

  data:
    redis:
      host: localhost
      port: 6379

  output:
    ansi:
      enabled: always

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ON_SECRET
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          google:
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # DTO 직렬화를 위해 JsonSerializer 사용
    consumer:
      group-id: course # Consumer Group ID
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # 모든 패키지의 클래스를 역직렬화 허용
      auto-offset-reset: earliest

  producer:
    # Kafka 클러스터에 대한 주소
    bootstrap-servers: localhost:9092

    # Kafka 메시지의 key를 직렬화할 때 사용할 클래스를 지정
    key-serializer: org.apache.kafka.common.serialization.StringSerializer

    # Kafka 메시지의 value를 직렬화할 때 사용할 클래스를 지정
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

custom:
  jwt:
    expire-seconds: "#{60 * 60}" # 1시간
    refresh-expire-seconds: "#{60 * 60 * 24 * 7}" # 1주일

app:
  registration-time:
    start: "09:00"
    duration-in-minutes: 720
