server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: dev
    include: secret

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            provider: kakao
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          google:
            provider: google
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: course
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest

app:
  registration-time:
    start: "09:00"
    duration-in-minutes: 900
