# application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      auto-startup: false

  mail:
    host: localhost
    port: 25

logging:
  level:
    org.springframework.test.context: DEBUG
