name: deploy
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'backend/**'
    branches: [ "main", "develop" ]
  pull_request:
    paths:
      - 'backend/**'
    branches: [ "main", "develop" ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      # 애플리케이션이 Redis 컨테이너에 접근할 수 있도록 호스트를 'redis'로 설정
      SPRING_DATA_REDIS_HOST: redis
      APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET }}

    # Redis 컨테이너를 서비스로 추가
    services:
      redis:
        image: redis:6.2-alpine # 가볍고 안정적인 Redis 이미지
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/settings.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: application-secret.yml 생성
        run: |
          echo "$APPLICATION_SECRET" > src/main/resources/application-secret.yml

      - name: Run tests with Gradle
        run: ./gradlew test -Dspring.data.redis.host=redis
      - name: Check Docker status
        run: docker info

  # 2. 릴리스 : main/develop 브랜치로 Push될 때만 실행
  makeTagAndRelease:
    name: Create Tag and Release
    if: github.event_name == 'push'
    needs: backend-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false

  # 3. 빌드 및 배포: main/develop 브랜치로 Push될 때만 실행
  buildImageAndPush:
    name: 도커 이미지 빌드와 푸시
    if: github.event_name == 'push'
    needs: makeTagAndRelease
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: application-secret.yml 생성
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET }}
        run: |
          echo "$APPLICATION_SECRET" > src/main/resources/application-secret.yml
      - name: Docker Buildx 설치
        uses: docker/setup-buildx-action@v2
      - name: 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: 빌드 앤 푸시
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/catch-course:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ env.OWNER_LC }}/catch-course:latest
